# Generated by Django 5.2.9 on 2025-12-27 02:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('number', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.rank_image_upload_to)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'number'), name='uniq_game_rank_name_number')],
            },
        ),
    ]
