# Generated by Django 5.2.9 on 2026-01-02 04:17

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0002_civilization_tournament_tournamententrant_and_more'), ('core', '0003_tournamentadmin_and_more')]

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('is_dlc', models.BooleanField(db_index=True, default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.civilization_image_upload_to)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='civilization_name_idx'), models.Index(fields=['is_dlc'], name='civilization_is_dlc_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_civilization_name')],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], db_index=True, default='DRAFT', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('game_gaps', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DROPPED', 'Dropped'), ('DISQUALIFIED', 'Disqualified')], db_index=True, default='ACTIVE', max_length=16)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrants', to='core.tournament')),
            ],
            options={
                'ordering': ['tournament_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntrantMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tournamententrant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entrant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entrant_id', '-is_captain', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tournamententrant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tournament_entrants', through='core.TournamentEntrantMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TournamentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tournament_invites', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.tournament')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('LEAGUE', 'League / Round Robin'), ('SINGLE_ELIM', 'Single Elimination')], db_index=True, max_length=16)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('best_of_default', models.PositiveSmallIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.tournament')),
            ],
            options={
                'ordering': ['tournament_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('best_of', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], db_index=True, default='SCHEDULED', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('score1', models.PositiveSmallIntegerField(default=0)),
                ('score2', models.PositiveSmallIntegerField(default=0)),
                ('winner_slot', models.PositiveSmallIntegerField(blank=True, help_text='1 or 2 when finished.', null=True)),
                ('entrant1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_entrant1', to='core.tournamententrant')),
                ('entrant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_entrant2', to='core.tournamententrant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournamentstage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MatchGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_number', models.PositiveSmallIntegerField(db_index=True)),
                ('winner_slot', models.PositiveSmallIntegerField(blank=True, help_text='1 or 2 when decided.', null=True)),
                ('entrant1_civ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_entrant1_civ', to='core.civilization')),
                ('entrant2_civ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_entrant2_civ', to='core.civilization')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.match')),
            ],
            options={
                'ordering': ['match_id', 'game_number', 'id'],
                'indexes': [models.Index(fields=['match'], name='match_game_match_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'game_number'), name='uniq_match_game_match_number')],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['name'], name='tournament_name_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status'], name='tournament_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['visibility'], name='tournament_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['created_by'], name='tournament_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['game_gaps'], name='tournament_game_gaps_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_tournament_name'),
        ),
        migrations.AddIndex(
            model_name='tournamententrantmember',
            index=models.Index(fields=['entrant'], name='entrant_member_entrant_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamententrantmember',
            index=models.Index(fields=['user'], name='entrant_member_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamententrantmember',
            constraint=models.UniqueConstraint(fields=('entrant', 'user'), name='uniq_tournament_entrant_member'),
        ),
        migrations.AddIndex(
            model_name='tournamententrant',
            index=models.Index(fields=['tournament'], name='entrant_tournament_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamententrant',
            index=models.Index(fields=['tournament', 'status'], name='entrant_tournament_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamententrant',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_entrant_name'),
        ),
        migrations.AddIndex(
            model_name='tournamentinvite',
            index=models.Index(fields=['tournament'], name='invite_tournament_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentinvite',
            index=models.Index(fields=['token'], name='invite_token_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentinvite',
            index=models.Index(fields=['is_active'], name='invite_is_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentinvite',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__isnull', True), ('uses__lte', models.F('max_uses')), _connector='OR'), name='chk_invite_uses_lte_max_uses'),
        ),
        migrations.AddIndex(
            model_name='tournamentstage',
            index=models.Index(fields=['tournament'], name='stage_tournament_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentstage',
            index=models.Index(fields=['tournament', 'type'], name='stage_tournament_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.UniqueConstraint(fields=('tournament', 'order'), name='uniq_stage_tournament_order'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['stage'], name='match_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='match_status_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['stage', 'round_number'], name='match_stage_round_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('stage', 'round_number', 'order'), name='uniq_match_stage_round_order'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('entrant1__isnull', True), ('entrant2__isnull', True), models.Q(('entrant1', models.F('entrant2')), _negated=True), _connector='OR'), name='chk_match_entrants_distinct'),
        ),
        migrations.CreateModel(
            name='TournamentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tournament_id', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='matchgame',
            name='uniq_match_game_match_number',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='tournament_created_by_idx',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='created_by',
        ),
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tournaments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchgame',
            name='winner_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='matchgame',
            constraint=models.UniqueConstraint(fields=('match', 'game_number'), name='uniq_match_game_number'),
        ),
        migrations.AddField(
            model_name='tournamentadmin',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_memberships', to='core.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_admin_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_tournaments', through='core.TournamentAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['owner'], name='tournament_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentadmin',
            index=models.Index(fields=['tournament'], name='tadmin_tourn_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentadmin',
            index=models.Index(fields=['user'], name='tadmin_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentadmin',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_tournament_admin_user'),
        ),
    ]
