# Generated by Django 5.2.9 on 2026-01-02 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_civilization_tournament_tournamententrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tournament_id', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='matchgame',
            name='uniq_match_game_match_number',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='tournament_created_by_idx',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='created_by',
        ),
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tournaments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchgame',
            name='winner_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='matchgame',
            constraint=models.UniqueConstraint(fields=('match', 'game_number'), name='uniq_match_game_number'),
        ),
        migrations.AddField(
            model_name='tournamentadmin',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_memberships', to='core.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_admin_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_tournaments', through='core.TournamentAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['owner'], name='tournament_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentadmin',
            index=models.Index(fields=['tournament'], name='tadmin_tourn_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentadmin',
            index=models.Index(fields=['user'], name='tadmin_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentadmin',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_tournament_admin_user'),
        ),
    ]
