# Generated by Django 5.2.9 on 2026-01-03 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_civilization_tournament_tournamententrant_and_more_squashed_0003_tournamentadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='starts_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
