# Generated by Django 5.2.9 on 2026-01-03 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tournament_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 14, 27, 57, 44400)),
            preserve_default=False,
        ),
    ]
