# Generated by Django 5.2.9 on 2026-01-03 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_tournament_ends_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="game_gaps",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gte", models.F("starts_at"))),
                name="chk_tournament_end_gte_start",
            ),
        ),
        migrations.RunSQL(
            sql="""
                -- 1) If an entrant has multiple captains, keep one randomly and demote the rest.
                WITH ranked AS (
                    SELECT
                        id,
                        ROW_NUMBER() OVER (PARTITION BY entrant_id ORDER BY RANDOM()) AS rn
                    FROM core_tournamententrantmember
                    WHERE is_captain = TRUE
                )
                UPDATE core_tournamententrantmember m
                SET is_captain = FALSE
                FROM ranked r
                WHERE m.id = r.id AND r.rn > 1;

                -- 2) If an entrant has no captain, promote one random member to captain.
                WITH candidates AS (
                    SELECT
                        m.id,
                        ROW_NUMBER() OVER (PARTITION BY m.entrant_id ORDER BY RANDOM()) AS rn
                    FROM core_tournamententrantmember m
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM core_tournamententrantmember c
                        WHERE c.entrant_id = m.entrant_id AND c.is_captain = TRUE
                    )
                )
                UPDATE core_tournamententrantmember m
                SET is_captain = TRUE
                FROM candidates c
                WHERE m.id = c.id AND c.rn = 1;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="tournamententrantmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True)),
                fields=("entrant",),
                name="uniq_tournament_entrant_captain",
            ),
        ),
    ]
