# Generated by Django 5.2.9 on 2026-01-04 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tournament_game_gaps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_memberships', to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tournament_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_tournaments', through='core.TournamentParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['team_size'], name='tournament_team_size_idx'),
        ),
        migrations.AddField(
            model_name='tournamentteamjoinrequest',
            name='entrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to='core.tournamententrant'),
        ),
        migrations.AddField(
            model_name='tournamentteamjoinrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_team_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentteamjoinrequest',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to='core.tournament'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament'], name='tpart_tourn_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['user'], name='tpart_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_tournament_participant_user'),
        ),
        migrations.AddIndex(
            model_name='tournamentteamjoinrequest',
            index=models.Index(fields=['tournament'], name='tteamreq_tourn_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteamjoinrequest',
            index=models.Index(fields=['entrant'], name='tteamreq_entrant_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteamjoinrequest',
            index=models.Index(fields=['requester'], name='tteamreq_requester_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentteamjoinrequest',
            index=models.Index(fields=['status'], name='tteamreq_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentteamjoinrequest',
            constraint=models.UniqueConstraint(fields=('entrant', 'requester'), name='uniq_tteam_joinreq_entrant_requester'),
        ),
    ]
