# Generated by Django 5.2.9 on 2026-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tournamentteamjoinrequest_tournament_team_size_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='uniq_tournament_name',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], db_index=True, default='REGISTRATION', max_length=16),
        ),
    ]
