# Generated by Django 5.2.9 on 2026-01-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tournament_uniq_tournament_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentstage',
            name='name',
        ),
    ]
