# Generated by Django 5.2.9 on 2025-12-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AoeWorldProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('in_game_name', models.CharField(max_length=150)),
                ('elo_solo', models.IntegerField(blank=True, null=True)),
                ('elo_team', models.IntegerField(blank=True, null=True)),
                ('hidden_elo_1v1', models.IntegerField(blank=True, null=True)),
                ('hidden_elo_2v2', models.IntegerField(blank=True, null=True)),
                ('hidden_elo_3v3', models.IntegerField(blank=True, null=True)),
                ('hidden_elo_4v4', models.IntegerField(blank=True, null=True)),
                ('rank_solo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.gamerank')),
                ('rank_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.gamerank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
