# Generated by Django 5.2.9 on 2025-12-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoeworldprofile',
            name='avatar_full',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aoeworldprofile',
            name='avatar_medium',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aoeworldprofile',
            name='avatar_small',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aoeworldprofile',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
