# Generated by Django 5.2.9 on 2025-12-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoe_world', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='aoe_world_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='in_game_name',
        ),
        migrations.AddField(
            model_name='user',
            name='aoe_world_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='aoe_world.aoeworldprofile'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('aoe_world_profile',), name='uniq_user_aoe_world_profile'),
        ),
    ]
