# Generated by Django 5.2.9 on 2025-12-29 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_remove_user_aoe_world_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('end_time', models.TimeField()),
                ('start_offset', models.PositiveIntegerField(db_index=True, editable=False)),
                ('end_offset', models.PositiveIntegerField(db_index=True, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'start_offset', 'id'],
                'indexes': [models.Index(fields=['user'], name='user_availability_user_idx'), models.Index(fields=['user', 'start_offset'], name='ua_user_start_off_idx'), models.Index(fields=['user', 'end_offset'], name='ua_user_end_off_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('start_offset'))), name='chk_user_availability_end_offset_gt_start_offset')],
            },
        ),
    ]
