# Generated by Django 5.2.9 on 2026-01-02 02:44

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_is_admin_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useravailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__lte', django.db.models.expressions.CombinedExpression(models.F('start_offset'), '+', models.Value(57600)))), name='chk_ua_max_span_16h'),
        ),
    ]
